---
title: "HTML Processing Assignment"
author: "Son Nam Nguyen"
date: "11/13/2021"
output: html_document
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}

# Loading packages with pacman
if (!require("pacman")) {
  install.packages("pacman")
}

pacman::p_load(tidyverse, rvest, data.table,
               xml2, stringr, kableExtra)

```

## One-page getter

I decided to chose scrape Stackoverflow posts having tags associated with an ELT tool called dbt (data build tool).
In the one-page getter function I took, post titles, view counts, vote scores, tags, and reference links.
After constructing the dataframe, I performed a data cleaning process.

```{r getpage}
url <- 'https://stackoverflow.com/questions/tagged/dbt'

get_one_page <- function(url) {
  t <- read_html(url)
  
relative_links <- t %>% 
    html_nodes('#questions .question-hyperlink') %>% html_attr('href')
  
links <- paste0(url, relative_links)
  
posts <- t %>% 
  html_nodes('#questions .question-hyperlink') %>% html_text()
  
views <- t %>% 
  html_nodes('.views') %>% html_text()

votes <- t %>% 
  html_nodes('.vote-count-post strong') %>% html_text()

tags <- t %>% 
  html_nodes('.t-dbt') %>% html_text()

df <- data.frame('title'=posts, 'tags'=tags, 'view_count'=views, 'score'=as.integer(votes), 'link'=links)

#Removing extra whitespaces and invisible characters from tags
df$tags <- gsub("[\r\n]", "", df$tags)
df$tags <- gsub('               ', ', ', df$tags)
df$tags <- gsub('    ', '', df$tags)

#Extract tags
df$tags <- sapply(strsplit(df$tags,","), `[`, 1)

#Set delimeter of tags
df$tags <- str_replace_all(df$tags, ' ',', ')

#Treat view_counts above 1000
df$view_count <- str_replace_all(df$view_count, 'k','000')

#Clean
df$view_count <- gsub("[\r\n]", "", df$view_count)
df$view_count <- gsub('    ', '', df$view_count)
df$view_count <- as.integer(sapply(strsplit(df$view_count," views"), `[`, 1))

  return(df)

} 
```

## Merge all pages

```{r bind}

links <- paste0('https://stackoverflow.com/questions/tagged/dbt?tab=newest&pagesize=50&page=', 1:6)

list_of_dfs<- lapply(links, get_one_page)

stackoverflow_dbt <- rbindlist(list_of_dfs)

kable(head(stackoverflow_dbt, 5), "html") %>% kable_styling("striped") %>% scroll_box(width = "100%")

```

